clusterGroup:
  name: standalone
  isHubCluster: false

  namespaces:
    - hello-world

  subscriptions: {}

  projects:
    - hello-world

  applications:
    hello-world:
      name: hello-world
      namespace: hello-world
      project: hello-world
      path: charts/hello-world
